# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz.xci
# IP: The module: 'CLK25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK25MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz.xci
# IP: The module: 'CLK25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lefev/Desktop/SpaceTerm/SpaceTerm.srcs/sources_1/ip/CLK25MHz/CLK25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
